import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ClerkProvider } from '@clerk/nextjs'

import ConvexClientProvider from "./ConvexClientProvider";

// This is a placeholder for getting the tenant's theme.
// In a real app, you would fetch this from the database based on the current tenant.
const theme = {
  primaryColor: '#4f46e5',
  secondaryColor: '#f3f4f6'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" style={{
        '--primary-color': theme.primaryColor,
        '--secondary-color': theme.secondaryColor,
      } as React.CSSProperties}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
